# Generated by Django 4.1.7 on 2024-05-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_default_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_active",
            field=models.BooleanField(default=False, verbose_name="邮箱验证状态"),
        ),
    ]
